create table if not exists order_composition
(
    product_id           bigint
        references product,
    ord_id               bigint
        references ord,
    quantity             integer not null,
    order_composition_id integer generated by default as identity
        primary key
);