create table if not exists account
(
    account_id bigint generated by default as identity
        primary key,
    username   varchar(20) not null,
    email      varchar(30) not null,
    password   varchar     not null,
    firstname  varchar(30) not null,
    surname    varchar(30) not null,
    role       varchar
);