create table if not exists ord
(
    ord_id      bigint generated by default as identity primary key,
    supplier_id bigint references supplier (supplier_id),
    account_id  bigint references account (account_id),
    ord_type    varchar      not null,
    date        timestamp(0) not null,
    amount      integer      not null
        constraint ord_amount_check check (amount > '-1'::integer)
)