create table if not exists order_composition
(
    product_id           bigint references product(product_id),
    ord_id               bigint references ord(ord_id),
    store_id             bigint references store(store_id),
    quantity             integer not null,
    order_composition_id integer generated by default as identity primary key
);