create table if not exists product
(
    product_id      bigint generated by default as identity primary key,
    title           varchar(50)  not null,
    date            timestamp(0) not null,
    presence        integer      not null constraint product_quantity_check check (presence > '-1'::integer),
    cost            integer,
    description     varchar,
    product_type_id bigint references product_type(product_type_id)
);